### ISSUE TITLE
The package published to npm as v1.6.4 does not include the module code

### ISSUE THREAD

**Issue by cschwebk** [mdx-js/eslint-mdx#116]
### Subject of the issue

The package published to npm as v1.6.4 does not include the module code.

![image](https://user-images.githubusercontent.com/1235114/70951723-0649ea00-2019-11ea-9ef4-ec38625f86bb.png)

**Comment by cschwebk** [comment]
Looks like `eslint-plugin-mdx` and `eslint-mdx` suffer from the same issue.

**Comment by JounQin** [comment]
@wooorm Oh, sorry, did you forget to run `yarn build` before publishing?

**Comment by JounQin** [comment]
@mdx-js/releasers Please help to publish `v1.6.5` and deprecated `v1.6.4`, run `yarn build` first before publishing.

**Comment by wooorm** [comment]
I ran several scripts outlined in `package.json`, but I’m guessing that the order was off (it seems the test script again removes everything?)

**Comment by JounQin** [comment]
@wooorm Yep, `clean` before `test` is required for better test coverage after my personal practice.
