### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by wooorm** [mdx-js/eslint-mdx#140]
### Subject of the feature

This project has the MDX defaults for support, contributing, issue/pr templates, etc, but some project-specific ways to contribute (e.g., how to publish) are unclear to me.

### Problem

I’m unsure what the procedure is to publish a release.

### Expected behavior

Documentation on which scripts to run, what to do, etc.

**Comment by JounQin** [comment]
Sorry @wooorm You published empty packages again as v1.6.6 without CHANGELOG files.😂

I'll add related documentations ASAP.

But could you run `yarn build && yarn run publish` again?

(And that's why I prefer CI deployment automatically again)

**Comment by wooorm** [comment]
@JounQin You already ran `yarn run publish`, creating the releases entry, the changeling entry, the commit, and the tag, so instead I ran `npm publish` on both packages, to release your changes.

**Comment by JounQin** [comment]
@wooorm You need to run `yarn build` first to build `lib` directories before deployment, I tried to run `yarn run publish` but I do not have npm publish permission, so you'll have to help to build and publish the npm packages manually.

Sorry again.

**Comment by wooorm** [comment]
There, that worked! Thanks for your patience.

For the publishing, `yarn build` is unneeded. `yarn run publish` already does that.
While running your suggested steps, I was not allowed to publish; for the contributing docs: you need to publish with a `GH_TOKEN` in the environment, like so: `GH_TOKEN=123123 yarn run publish`

**Comment by JounQin** [comment]
> For the publishing, `yarn build` is unneeded. `yarn run publish` already does that.

@wooorm That seems not correct to me. `prepublishOnly` will not run on script `publish`.

I decide to rename them to `predeploy` and `deploy`, how do you think?

**Comment by wooorm** [comment]
> That seems not correct to me. prepublishOnly will not run on script publish.

Interesting! I did `yarn build` first, and I believe in the log for `publish` I saw the same build printed again! 🤷‍♂️

> I decide to rename them to predeploy and deploy, how do you think?

I have no real opinions on this!
To iterate my stance on npm tokens again: my preference is to not automate publishes, but if MDX releasers want to do it, that’s fine!

**Comment by JounQin** [comment]
@mdx-js/releasers So releasers, how do you think about publishing on CI automatically?

**Comment by silvenon** [comment]
I don't have experience with it, so I'm initially uncomfortable with that idea, but I think eventually this should be a part of popular projects _as long as they're well set up_, so I'm open to trying. I'd need to educate myself about this first, though. @JounQin do you already have much experience with this to explain this process and the challenges you faced in the past? I suggest opening a new issue about this proposition, mentioning releasers.
