### ISSUE TITLE
eslint-plugin-mdx triggering mdx/no-unescaped-entities inside JSX

### ISSUE THREAD

**Issue by NickyMeuleman** [mdx-js/eslint-mdx#158]
Saw the
> Need help?
> Please ask on Spectrum

and

> This is *not* a place to ask questions.  For that, go to [Spectrum]> > 
> (https://spectrum.chat/mdx)

So asked there first.

### Subject of the issue

eslint-plugin-mdx triggering mdx/no-unescaped-entities inside JSX
![Code_7IO2sDBmqf](https://user-images.githubusercontent.com/30179461/74610311-6ed54600-50f2-11ea-999a-3b8121c03afa.png)

### Your environment

*   **OS**: Windows 10 using WSL2 Ubuntu Bionic Beaver
*   **Packages**: eslint-plugin-mdx
*   **Env**: node 12, yarn 1.17

### Steps to reproduce

Clone and run `yarn`: https://github.com/NickyMeuleman/gatsby-theme-nicky-blog.git
Look at any React component in `.mdx` that passes a prop with a string value.
Example `<YouTube youTubeId="dQw4w9WgXcQ" />`
https://github.com/NickyMeuleman/gatsby-theme-nicky-blog/blob/master/demo/data/posts/i-want-it-all/index.mdx#L27

### Expected behaviour

No mdx/no-unescaped-entities error for the quotes in `<YouTube youTubeId="dQw4w9WgXcQ" />`

### Actual behaviour

mdx/no-unescaped-entities error

**Comment by JounQin** [comment]
@NickyMeuleman You can add an empty line as workaround for now, I'll take a look ASAP.

**Comment by JounQin** [comment]
@NickyMeuleman Sorry for the delay, it should be fixed after #196 been merged and released.

**Comment by JounQin** [comment]
@NickyMeuleman Can you try v1.6.9?

**Comment by NickyMeuleman** [comment]
Can confirm I no longer get the error.
This is a screenshot I just took in the same file
![image](https://user-images.githubusercontent.com/30179461/79069341-bd0b5d80-7ccd-11ea-9585-a11e93c4f9bc.png)
