### ISSUE TITLE
Auto fix jsx style comments in html block to html comments

### ISSUE THREAD

**Issue by JounQin** [mdx-js/eslint-mdx#18]
```jsx
// input
Inline <Test>{/* it's a comment */}</Test>

// fixed output
Inline <Test><!-- it's a comment --></Test>
```

Which is an opposite of #13.

**Comment by JounQin** [comment]
@mdx-js/maintainers I'm wondering whether it works as expected.

```mdx
Inline <Button>{/_ it's a comment _/}</Button>

<Button>{/* it's a comment */}</Button>
```

![image](https://user-images.githubusercontent.com/8336744/73609134-a4b00000-4605-11ea-87e8-1f76f8095198.png)

They are not consistent IMO.

**Comment by wooorm** [comment]
I don’t understand, could you expand on what your question is?

**Comment by JounQin** [comment]
@wooorm Hmm... Did you see my capture of playground? Same "jsx" content emits different outputs due to "inline" paragraph(sorry I'm a native English speeker😂).

In "inline" mode, the "jsx" children are considered as markdown content, what makes true jsx comments impossible.

**Comment by wooorm** [comment]
I saw your code! Right!

So, there is a big difference between “inline” and “block” JSX.

Taking a different example, `Inline <i>**emphasis and importance**</i>` is “inline” (the markdown works), whereas `<div>\n**no importance, this doesn’t work**\n</div>` is block (the markdown doesn’t work).

See also: https://github.com/mdx-js/mdx/issues/628
