### ISSUE TITLE
Support for MDX v2

### ISSUE THREAD

**Issue by johno** [mdx-js/eslint-mdx#204]
Thanks for the amazing package @JounQin!

For v2 it looks like we'll need to change a few things with this package, it's currently silently failing when run in the `next` branch of [mdx-js/mdx](https://github.com/mdx-js/mdx). Will you have any time in the next month or so to ensure compatibility?

```
~/c/mdx next ⇡
❯ yarn lint
yarn run v1.17.3
$ eslint . --cache --ext js,jsx,md,mdx -f friendly

Oops! Something went wrong! :(

ESLint: 7.0.0


error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/c/mdx next 6s
```

**Comment by JounQin** [comment]
Sure, I'll take a look ASAP.

**Comment by JounQin** [comment]
@johno https://github.com/mdx-js/eslint-mdx/commit/80686eb0e9cb7e0f8d468d9616b85c1f7ebc6cca#commitcomment-38853669 
This commit has not been published yet, that's why ESLint breaks.

**Comment by JounQin** [comment]
@johno @wooorm So would like publish a new version?

**Comment by wooorm** [comment]
Done

**Comment by JounQin** [comment]
```sh
# yarn 1
yarn add https://pkg.csb.dev/mdx-js/eslint-mdx/commit/b58571cd/eslint-mdx https://pkg.csb.dev/mdx-js/eslint-mdx/commit/b58571cd/eslint-plugin-mdx
# yarn 2, 3
yarn add eslint-mdx@https://pkg.csb.dev/mdx-js/eslint-mdx/commit/b58571cd/eslint-mdx/_pkg.tgz eslint-plugin-mdx@https://pkg.csb.dev/mdx-js/eslint-mdx/commit/b58571cd/eslint-plugin-mdx/_pkg.tgz
# npm
npm i https://pkg.csb.dev/mdx-js/eslint-mdx/commit/b58571cd/eslint-mdx https://pkg.csb.dev/mdx-js/eslint-mdx/commit/b58571cd/eslint-plugin-mdx
```

Please help us to test the fresh new version.
