### ISSUE TITLE
Invalid character for md syntax

### ISSUE THREAD

**Issue by tiagoporto** [mdx-js/eslint-mdx#230]
### Issue

In mdx file I have a mix of HTML and markdown. eslint-plugin-mdx is not recognizing md syntax.

![Screen Shot 2020-08-31 at 2 20 31 PM](https://user-images.githubusercontent.com/3688905/91747832-4ba54c00-eb95-11ea-97d8-347336eb0076.png)

After remove markdown code works

![Screen Shot 2020-08-31 at 2 25 09 PM](https://user-images.githubusercontent.com/3688905/91748126-d4bc8300-eb95-11ea-971c-c325ebdf865f.png)

### Your environment

*   **OS**: Mac OS 10.15.5
*   **Packages**: `eslint: 7.7.0` - `eslint-plugin-mdx: 1.8.2` - `typescript: 4.0.2`
*   **Env**: npm

.eslintrc
```json
{
  "env": {
    "browser": true,
    "jest/globals": true
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "parser": "@typescript-eslint/parser",
  "extends": [
    "standard",
    "eslint:recommended",
    "plugin:jest/recommended",
    "plugin:react-hooks/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "prettier",
    "prettier/react",
    "prettier/@typescript-eslint",
    "prettier/standard",
    "plugin:mdx/recommended"
  ],
  "plugins": ["@typescript-eslint", "react", "react-hooks", "standard", "jest"]
}
```

**Comment by JounQin** [comment]
`.mdx` files require `eslint-mdx` as parser, but you're wrongly using `@typescript-eslint/parser`, you can try to use `overrides` instead:

```jsonc
{
  "overrides": [
    {
      "files": "*.mdx",
      // "parser": "eslint-mdx", // enable `eslint-mdx` manually if it does not work
      "extends": "plugin:mdx/recommended"
    }
  ]
}
```

**Comment by tiagoporto** [comment]
Thank you @JounQin, it worked.

Just for curiosity, when you said `but you're wrongly using @typescript-eslint/parser`, could you explain what Im doing wrong?

Thanks one more time.

**Comment by JounQin** [comment]
@tiagoporto 

> `.mdx` files require `eslint-mdx` as parser

I mean `@typescript-eslint/parser` overrides `eslint-mdx` as default parser in your config.

**Comment by tiagoporto** [comment]
Cool, I was thinking config was wrong.
I can improve it adding ts parser only for tsx and ts file.
Thanks again.
