### ISSUE TITLE
Parsing error: unknown jsx node

### ISSUE THREAD

**Issue by JohnCasab** [mdx-js/eslint-mdx#266]

**Comment by JounQin** [comment]
Without runnable reproduction, I can help to debug.

**Comment by alexkrautmann** [comment]
@JounQin I came across this when looking for a solution to what I think is the same issue.

Minimal repro in this [code sandbox](https://codesandbox.io/s/youthful-keller-bj6c1). My actual config is much more complex, but I tried to reduce it down to the smallest repro possible. In this sandbox, you can run `yarn lint` from a terminal. Notice that the file `test-line-between.mdx` errors, but the file `test-no-line-between.mdx` does not error.

Let me know if you want me to create a separate github issue.

**Comment by JounQin** [comment]
close in favor of #272
