### ISSUE TITLE
[feature] add support for linting code blocks

### ISSUE THREAD

**Issue by JounQin** [mdx-js/eslint-mdx#278]
We can already get code blocks in `eslint-mdx`, so it should be possible to lint them by `eslint-plugin-mdx` itself.

A setting named `lintCodeBlocks: boolean` should be required.

Additional, we can reference `eslint-plugin-markdown`'s codes.

**Comment by JounQin** [comment]
@chenxsan Please try v1.10.0 with settings `"mdx/code-blocks": true`, `"processor": "mdx/remark"` is configed automatically, don't use `"processor": "markdown/markdown"`.

**Comment by chenxsan** [comment]
@JounQin Thanks for your work, I'll test it soon.

**Comment by JounQin** [comment]
Due to an unreleased bugfix https://github.com/mdx-js/eslint-mdx/pull/285, you need to provide a `remark` config temporarily.
