### ISSUE TITLE
1.10.0 update causes a "TypeError: Cannot read property 'config' of null"

### ISSUE THREAD

**Issue by codylindley** [mdx-js/eslint-mdx#290]
When moving from 1.9.0 to 1.10.0 I get the error, `TypeError: Cannot read property 'config' of null` even when the .mdx file is completely empty.

**Comment by ChristianMurphy** [comment]
https://github.com/mdx-js/eslint-mdx/pull/285

**Comment by YutaUra** [comment]
https://github.com/mdx-js/eslint-mdx/pull/285#issuecomment-800883404
