### ISSUE TITLE
rebass is installed

### ISSUE THREAD

**Issue by chenxsan** [mdx-js/eslint-mdx#294]
### Subject of the issue

One thing I noticed is that `rebass` is an [`optionalDependencies `](https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-plugin-mdx/package.json#L46), so yarn is going to install it whenever possible as per https://classic.yarnpkg.com/en/docs/dependency-types/, and it installs quite a lot of packages https://github.com/webpack/webpack.js.org/pull/4326/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de.

But I don't use `rebass` at all, hence it just doesn't make sense.

### Steps to reproduce

Just install `eslint-plugin-mdx` and check `yarn.lock` for `rebass`.

### Expected behaviour

`rebass` should not be installed just because I have `eslint-plugin-mdx` installed.

### Actual behaviour

`rebass` is installed along with `eslint-plugin-mdx`.

**Comment by JounQin** [comment]
PR welcome to move it to root `package.json` as dev dep.
