### ISSUE TITLE
Upgrade `remark-parse` dependency in `eslint-mdx`

### ISSUE THREAD

**Issue by 01taylop** [mdx-js/eslint-mdx#370]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.16.0

### Steps to reproduce

The dependency `trim` has a "high severity" vulnerability being flagged in GitHub's Dependabot alerts.

The `eslint-mdx` package is using `trim` via `remark-parse ^8.0.3` in [packages/eslint-mdx/package.json](https://github.com/mdx-js/eslint-mdx/blob/062aad5440be6546d8f2fcf78bfd540b2b2b26e4/packages/eslint-mdx/package.json#L36).

Since version 9.0.0, `remark-parse` has not used the `trim` dependency ([commit](https://github.com/remarkjs/remark/commit/6b42465526bb15f70d98a0ea0daccea01ffb8004#diff-0828111e0233dec7891d8f0d6a9f496957215446a0935a1c71e22cc6c6c1760c)).

### Expected behavior

Using the latest version of `eslint-plugin-mdx` should not cause a Dependabot alert.

### Actual behavior

Using the latest version of `eslint-plugin-mdx` causes a Dependabot alert.

### Runtime

Node v16

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

webpack

**Comment by JounQin** [comment]
duplicate of #312
