### ISSUE TITLE
/README.md   1:4  error  Parsing error: Missing semicolon. (1:4)

### ISSUE THREAD

**Issue by jlarmstrongiv** [mdx-js/eslint-mdx#378]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Both the current 1.17.0 and 2.0.0-next.1

### Steps to reproduce

Can email example upon request

### Expected behavior

Linting works without crashing!

### Actual behavior

This is a markdown file, but it treats it like `mdx`.

```
/Users/user/Desktop/next-app/README.md
  1:4  error  Parsing error: Missing semicolon. (1:4)

✖ 1 problem (1 error, 0 warnings)
```

### Runtime

Node v14

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

webpack, esbuild, Next.js

**Comment by JounQin** [comment]
Please provide a correct reproduction.

**Comment by jlarmstrongiv** [comment]
@JounQin Can you provide an email to send it to?

**Comment by JounQin** [comment]
@jlarmstrongiv Please use GitHub repository for a minimal reproduction, we don't want a complicated one.

**Comment by jlarmstrongiv** [comment]
Sorry, I am unable to provide a reproduction at this time.

**Comment by JounQin** [comment]
@jlarmstrongiv See https://github.com/mdx-js/eslint-mdx#notice

**Comment by jlarmstrongiv** [comment]
Was able to make a reproduction for most monorepo errors after returning home https://github.com/jlarmstrongiv/eslint-mdx-reproduction but your link got me on the right track and fixed it 👍 unfortunately, I could never get it to work with keystonejs
