### ISSUE TITLE
`eslint-plugin-mdx` doesn't seems to load `.remarkrc.mjs`

### ISSUE THREAD

**Issue by JulianCataldo** [mdx-js/eslint-mdx#436]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

All latest

### Link to runnable example

https://github.com/JulianCataldo/eslint-mdx-repro

### Steps to reproduce

Hello!

Here is a minimal reproduction repository I've made to illustrate this issue:

https://github.com/JulianCataldo/eslint-mdx-repro

Steps to repro. are described in its README.

I've talked about it before here:
https://github.com/remarkjs/remark-lint/issues/300

Was not quite sure were in the stack is the culprit (remark? eslint? eslint-mdx? cosmic-config?).

For now, creating a static config file (as YAML or JSON) seems to work fine, so ESLint is good with 100% ESMs remark plugins (through the MDX plugin).

But that means having to maintain two remark-lint config, one for MDX and one for MD.

Maybe I've overlooked something?

Many thanks :)

### Expected behavior

`.remarkrc.mjs` loaded from both `remark` and `eslint`

### Actual behavior

Module JS configs are not loaded by the ESLint plugin.

**Comment by JounQin** [comment]
https://github.com/davidtheclark/cosmiconfig#searchplaces

PR welcome to add this support at https://github.com/mdx-js/eslint-mdx/blob/a1998c787f0049ae0cd705fc51f079c63ded75b2/packages/eslint-mdx/src/worker.ts#L60-L62

**Comment by JounQin** [comment]
Maybe we should migrate to use [`unified-engine`](https://github.com/unifiedjs/unified-engine) instead.
