### ISSUE TITLE
Parsing error mdx: Missing semicolon

### ISSUE THREAD

**Issue by Manubi** [mdx-js/eslint-mdx#453]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

eslint: 8.32.0, eslint-config-next: 13.2.3

### Link to runnable example

https://github.com/Manubi/manuelbichler.com

### Steps to reproduce

Just pull the repo and go into `src/pages/articles`.

### Expected behavior

There shouldn't be an error.

### Actual behavior

Displays `Parsing error: Missing semicolon.`
![CleanShot 2023-03-07 at 10 11 04](https://user-images.githubusercontent.com/20935138/223376280-8e737887-26b5-4727-aa72-a4fceb4797ad.png)

### Runtime

Node v16

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
@Manubi the reproduction you shared shows as 404 not found, did you make it private or delete it?

**Comment by Manubi** [comment]
@ChristianMurphy sorry my bad. Made it public.

**Comment by ChristianMurphy** [comment]
@Manubi I'm a bit confused, you aren't using ESLint MDX, and looking at git history have never used it.
https://github.com/Manubi/manuelbichler.com/blob/c66216f69d35067beed086cbefd87bc8656e19f2/.eslintrc.json#L2

The solution if you'd like MDX to be parsed by ESlint is to, add `eslint-plugin-mdx` following the guide from the README https://github.com/mdx-js/eslint-mdx/tree/master/packages/eslint-plugin-mdx
