### ISSUE TITLE
Document usage in flat config

### ISSUE THREAD

**Issue by levino** [mdx-js/eslint-mdx#455]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

It is unclear how to use this package with the new eslint flat config.

### Solution

Provide documentation on how to use this package with an eslint flat config. Potentially one would have to show how to use the [backwards compatibility](https://eslint.org/blog/2022/08/new-config-system-part-2/#backwards-compatibility-utility) tool until the exports of this library have been changed.

### Alternatives

I would say no.

**Comment by JounQin** [comment]
Basically, it should be something like following:

```js
// eslint.config.js

import * as eslintMdx from 'eslint-mdx'
import * as mdx from 'eslint-plugin-mdx'

export default [
  {
    files: ['**/*.mdx'],
    plugins: {
      mdx,
    },
    languageOptions: {
      parser: eslintMdx,
    },
    processor: mdx.processors.remark,
    settings: {
      'mdx/code-blocks': true, // this won't work sadly
    },
    rules: {
      'no-console': 'error',
    },
  },
]
```

We're blocked by https://github.com/eslint/eslint/pull/12068

**Comment by bodograumann** [comment]
Can you please also provide instructions for how to use the plugin together with prettier when using flat config? I think this is still the old config syntax: https://github.com/mdx-js/eslint-mdx?tab=readme-ov-file#prettier-integration

**Comment by JounQin** [comment]
> Can you please also provide instructions for how to use the plugin together with prettier when using flat config? I think this is still the old config syntax: [mdx-js/eslint-mdx#prettier-integration](https://github.com/mdx-js/eslint-mdx?tab=readme-ov-file&rgh-link-date=2025-03-20T08%3A25%3A49.000Z#prettier-integration)

That part is for `.remarkrc`, not `.eslintrc`.

For ESLint, links for https://github.com/prettier/eslint-config-prettier and https://github.com/prettier/eslint-plugin-prettier could be added, would you like to raise a PR?
