### ISSUE TITLE
Incompatible w/ MDX v3?

### ISSUE THREAD

**Issue by jaswrks** [mdx-js/eslint-mdx#480]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.2.0

### Steps to reproduce

> Parsing error: Cannot set properties of undefined (setting 'inTable') eslint

Getting [this error](https://github.com/remarkjs/remark-gfm/issues/57) after updating to MDX v3.
- Can someone confirm that eslint-mdx is not yet compatible with MDX v3?

```
"@mdx-js/mdx": "^3.0.0",


        "eslint": "8.54.0",
        "eslint-plugin-mdx": "2.2.0",

        "remark": "^15.0.1",
        "remark-directive": "^3.0.0",
        "remark-frontmatter": "^5.0.0",
        "remark-gfm": "^4.0.0",
        "remark-lint": "^9.1.2",
        "remark-mdx-frontmatter": "^4.0.0",
        "remark-mermaidjs": "^6.0.0",
        "remark-preset-lint-recommended": "^6.1.3",
        "remark-preset-prettier": "^2.0.1",
        "remark-smartypants": "^2.0.0",
```

```
---
Foo: Bar
---

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

![Markup on 2023-11-26 at 01:28:43](https://github.com/contentlayerdev/contentlayer/assets/1563559/80a32ae8-d9ed-4b91-8eb7-58f4b3881e2c)

### Expected behavior

ESLint works propertly using MDX v3.

### Actual behavior

ESLint error:

> Parsing error: Cannot set properties of undefined (setting 'inTable') eslint

### Runtime

Node v19

### Package manager

npm v9

### OS

macOS

### Build and bundle tools

Vite

**Comment by JounQin** [comment]
PR welcome, I think that would be very smooth by just upgrading dependencies.

**Comment by jaswrks** [comment]
Thanks. PR: https://github.com/mdx-js/eslint-mdx/pull/481
