### ISSUE TITLE
on npm eslint-plugin-mdx v2.3.2 is tagged as latest while v3.1.3 should be

### ISSUE THREAD

**Issue by ajslater** [mdx-js/eslint-mdx#517]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

eslint-plugin-mdx 3.1.3

### Steps to reproduce

```sh
$ npm outdated
Package            Current  Wanted  Latest  Location
eslint-plugin-mdx    3.1.3   3.1.3   2.3.2  node_modules/eslint-plugin-mdx
```

### Expected behavior

v3.1.3 should be tagged as latest and npm outdated would not show v3.1.3 as "outdated"

### Actual behavior

v3.1.3 is marked as not the latest version by npm outdated.

### Runtime

Node v21

### Package manager

npm v10

### OS

macOS

### Build and bundle tools

Vite

**Comment by JounQin** [comment]
Sorry, I'll take a look.

**Comment by JounQin** [comment]
<img width="829" alt="image" src="https://github.com/mdx-js/eslint-mdx/assets/8336744/e866dcff-b0e5-4c28-b66f-6b1d70463a8e">

Fixed.
